services:
  koel:
    image: leonhatches/koel-app:latest
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=koel
      - DB_USERNAME=koel
      - DB_PASSWORD=koel
      - APP_URL=http://localhost
    volumes:
      - ./musica:/music
      - image_storage:/var/www/html/storage/app/public/images
      - search_index:/var/www/html/storage/search-indexes

  database:
    image: mariadb:10.11
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=koel
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=koel

volumes:
  db:
    driver: local
  image_storage:
    driver: local
  search_index:
    driver: local